### ISSUE TITLE
Why does envjson linger after validation?

### ISSUE THREAD

**Issue by philpennock** [apg/envjson#4]
I read http://sigusr2.net/envjson.html and took a look at the code; thanks for this tool, it's a good idea.

I'm perplexed by one thing: when running a command why forward signals and linger around as a separate process, instead of exec'ing the actual command?  The Unix command-wrapper idiom is to modify current process state and then exec-to-replace.  In Golang, that's using `syscall.Exec()`

Is this a portability concern or something?

**Comment by apg** [comment]
Thanks, Phil! 
You're completely right. This should simply `execve`. I thought about it, and then realized I didn't know how to do it in Go. For whatever reason I never considered the syscall package, which I feel silly about now. I'll fix it tonight.
